# backend:
#   name: github
#   repo: DaanBoertien/First-Jekkyl-website

backend:
  name: github
  branch: master
  repo: DaanBoertien/First-Jekkyl-website

media_folder: assets/img/uploads/

collections:
  - name: "test"
    label: "test"
    files:
      - name: "test"
        label: "Test files"
        file: "_data/test.yml"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Hello!"
            name: "hello"
            widget: "string"
          - label: "Greet me"
            name: "greeting"
            widget: "string"
  - name: "concerts"
    label: "Concerts"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    editor:
      preview: false
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "concert",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "place", name: "time", widget: "string" }
      - { label: "More information", name: "body", widget: "markdown" }
  - name: "media"
    label: "Media"
    files:
      - name: "videos"
        label: "Video's"
        file: "_data/videos.yml"
        editor:
          preview: false
        fields:
          - label: "Video's"
            label_singular: "Video"
            name: "video"
            widget: "list"
            add_to_top: true
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "YouTube Id"
                name: "youtube-id"
                widget: "string"
      - name: "photos"
        label: "Foto's"
        file: "_data/photos.yml"
        editor:
          preview: false
        fields:
          - label: "Foto's"
            label_singular: "Foto"
            name: "foto"
            widget: "list"
            add_to_top: true
            fields:
              - label: "Foto"
                name: "url"
                widget: "image"
              - label: "Alt tekst"
                name: "alt"
                widget: "string"
              - label: "Fotograaf"
                name: "photographer"
                widget: "string"
