# backend:
#   name: github
#   repo: DaanBoertien/First-Jekkyl-website

backend:
  name: github
  branch: master
  repo: DaanBoertien/First-Jekkyl-website

media_folder: assets/img/uploads/

collections:
  - name: "concerts"
    label: "Concerts"
    label_singular: "Concert"
    folder: "_concerts/"
    create: true
    sortable_fields: ["date"]
    summary: "{{hall}}, {{place}}, {{ concert_date }}"
    slug: "{{concert_date}}-{{hall}}"
    editor:
      preview: false
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "concert",
        }
      - { label: "Zaal", name: "hall", widget: "string" }
      - {
          label: "Datum",
          name: "concert_date",
          widget: "datetime",
          # date_format: "DD-MM-YYYY",
          time_format: false,
        }
        # format: "YYYY-MM-DD",
      - {
          label: "Tijd",
          name: "concert_time",
          widget: "datetime",
          date_format: false,
          time_format: "HH:mm",
        }
        # format: "HH:mm",

      - { label: "Plaats", name: "place", widget: "string" }
      - { label: "Repertoire", name: "repertoire", widget: "string" }
      - { label: "Musici", name: "musicians", widget: "text" }
      - {
          label: "Link naar organisator",
          name: "organizer_url",
          widget: "text",
          required: false,
        }
      - {
          label: "In archief",
          name: "in_archive",
          widget: "boolean",
          default: true,
          required: false,
        }
      - {
          label: "Geannuleerd",
          name: "cancelled",
          widget: "boolean",
          default: false,
          required: false,
        }

  - name: "media"
    label: "Media"
    files:
      - name: "videos"
        label: "Video's"
        file: "_data/videos.yml"
        editor:
          preview: false
        fields:
          - label: "Video's"
            label_singular: "Video"
            name: "video"
            widget: "list"
            add_to_top: true
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "YouTube Id"
                name: "youtube-id"
                widget: "string"
      - name: "photos"
        label: "Foto's"
        file: "_data/photos.yml"
        editor:
          preview: false
        fields:
          - label: "Foto's"
            label_singular: "Foto"
            name: "foto"
            widget: "list"
            summary: "{{fields.alt}}"
            add_to_top: true
            fields:
              - label: "Foto"
                name: "url"
                widget: "image"
              - label: "Alt tekst"
                name: "alt"
                widget: "string"
              - label: "Fotograaf"
                name: "photographer"
                widget: "string"
                required: false
